[theme]
name = "solarized-light"

[theme.overrides]
idle_fg = "#657b83"
separator = ""

[icons]
name = "material-nf"

[[block]]
block = "cpu"
icons_format = " "
format = "{barchart} {utilization}"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
clickable = true
icons_format = " {icon}"
format_mem = "{mem_used_percents} {mem_used}"
format_swap = "{swap_used_percents} {swap_used}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
icons_format = "{icon}"
format = "{icon} {available}"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "uptime"
icons_format = " "

[[block]]
block = "battery"
driver = "sysfs"
device = "BAT0"
icons_format = " {icon} "
format = "{percentage}"

[[block]]
block = "time"
icons_format = " "
interval = 5
format = "%a/%U %H:%M %Y-%m-%d"
