# Show terminal colors and their role in my theme.
function colors {
	local -r start="\033[0;48;5;"
	local -r end="m"
	local -r reset="\033[0m"

	local -r black="${start}0${end} ${reset}"
	local -r red="${start}1${end} ${reset}"
	local -r green="${start}2${end} ${reset}"
	local -r yellow="${start}3${end} ${reset}"
	local -r blue="${start}4${end} ${reset}"
	local -r magenta="${start}5${end} ${reset}"
	local -r cyan="${start}6${end} ${reset}"
	local -r white="${start}7${end} ${reset}"
	local -r brightblack="${start}8${end} ${reset}"
	local -r brightred="${start}9${end} ${reset}"
	local -r brightgreen="${start}10${end} ${reset}"
	local -r brightyellow="${start}11${end} ${reset}"
	local -r brightblue="${start}12${end} ${reset}"
	local -r brightmagenta="${start}13${end} ${reset}"
	local -r brightcyan="${start}14${end} ${reset}"
	local -r brightwhite="${start}15${end} ${reset}"
	
	printf " $black 0  BLACK\t\tbackground\n"
	printf " $red 1  RED\t\talert\n"
	printf " $green 2  GREEN\t\tinverse accent\n"
	printf " $yellow 3  YELLOW\t\taccent\n"
	printf " $blue 4  BLUE\t\thyper\n"
	printf " $magenta 5  MAGENTA\t\tmajor\n"
	printf " $cyan 6  CYAN\t\tsuper\n"
	printf " $white 7  WHITE\t\tinverse emphasized background\n"
	printf " $brightblack 8  BRIGHTBLACK\temphasized background\n"
	printf " $brightred 9  BRIGHTRED\t\tattention\n"
	printf " $brightgreen 10 BRIGHTGREEN\tdeemphasized foreground\n"
	printf " $brightyellow 11 BRIGHTYELLOW\tinverse foreground\n"
	printf " $brightblue 12 BRIGHTBLUE\tforeground\n"
	printf " $brightmagenta 13 BRIGHTMAGENTA\tminor\n"
	printf " $brightcyan 14 BRIGHTCYAN\temphasized foreground\n"
	printf " $brightwhite 15 BRIGHTWHITE\tinverse background\n"
}
