{ config, nixosConfig, ... }:

let
  home = "${config.home.homeDirectory}";
  hostname = "${nixosConfig.networking.hostName}";
  keepFileContents = ''
    This file was generated by my NixOS configuration so that its parent
    directory is created. You can modify this file, but on the next invocation
    of

      sudo nixos-rebuild switch

    it will be restored to this text and any changes will by lost.
  '';
in
{
  xdg.enable = true;

  xdg.userDirs.enable = true;
  xdg.userDirs.createDirectories = false;
  xdg.userDirs.desktop = "${home}/desktop";
  xdg.userDirs.documents = "${home}/documents";
  xdg.userDirs.download = "${home}/downloads";
  xdg.userDirs.music = "${home}/music";
  xdg.userDirs.pictures = "${home}/images";
  xdg.userDirs.publicShare = "${home}/public"; # Shouldn't exist.
  xdg.userDirs.templates = "${home}/templates"; # Shouldn't exist.
  xdg.userDirs.videos = "${home}/videos";

  # TODO xdg: setup systemd.user.tmpfiles.rules to clean up user directories.

  home.file."projects/code/benjaminedwardwebb/.keep".text = keepFileContents;
  home.file."notes/.keep".text = keepFileContents;

  home.file."hosts/.keep".text = keepFileContents;
  home.file."hosts/${hostname}/.keep".text = keepFileContents;
  home.file."hosts/${hostname}/secrets/.keep".text = keepFileContents;
  home.file."hosts/${hostname}/dynamic/.keep".text = keepFileContents;
  # A third directory, named "static", is expected under ~/hosts/${hostname}.
  # It's a directory containing additional nix (Home-Manager) configuration
  # that is host-specific. It's not created here because it's setup manually on
  # each host. It's usually a symlink to a checked out git repository. It's
  # contents are loaded elsewhere in this Home-Manager configuration, and when
  # they are the possibility that it doesn't exist should be accounted for.
  # See: ./README.md
}
