{ config, pkgs, lib, ... }:

let
  home = "${config.home.homeDirectory}";
  keepFileContents = ''
    This file was generated by my NixOS configuration so that its parent
    directory is created. You can modify this file, but on the next invocation
    of

      sudo nixos-rebuild switch

    it will be restored to this text and any changes will by lost.
  '';
in
{
  xdg.enable = true;

  xdg.userDirs.enable = true;
  xdg.userDirs.createDirectories = false;
  xdg.userDirs.desktop = "${home}/desktop";
  xdg.userDirs.documents = "${home}/documents";
  xdg.userDirs.download = "${home}/downloads";
  xdg.userDirs.music = "${home}/music";
  xdg.userDirs.pictures = "${home}/images";
  xdg.userDirs.publicShare = "${home}/public";
  xdg.userDirs.templates = "${home}/templates";
  xdg.userDirs.videos = "${home}/videos";

  # TODO xdg: setup systemd.user.tmpfiles.rules to clean up user directories.

  home.file."projects/code/benjaminedwardwebb/.keep".text = keepFileContents;
  home.file."notes/.keep".text = keepFileContents;
  home.file."hosts/.keep".text = keepFileContents;
}
